server:
  port: 9999

spring:
  datasource:
    url: jdbc:mysql://192.168.1.164:3306/seventeen?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: jindi
    password:  jindi
    driver-class-name: com.mysql.jdbc.Driver
#  jpa:
#    database: mysql
#    show-sql: true
#    hibernate:
#      ddl-auto: update